name: .NET

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Publish
      run: dotnet publish -c Release -p:PublishProfile=FolderProfile
    - name: Prepare server
      uses: garygrossgarten/github-action-ssh@v0.6.3
      with:
          command: sudo systemctl stop crowbarwebsite.service
          host: ${{ secrets.HOST }}
          username: deployaccount
          privateKey: ${{ secrets.PRIVATEKEY }}
    - name: gha-ssh
  # You may pin to the exact commit or the version.
  # uses: ryanchapman/gha-ssh@e4d012399f3d2643d6bf1c4dcb69daa8d572f083
      uses: ryanchapman/gha-ssh@v1
      with:
          authorized_github_users: nzgamer41
    - name: Copy folder content recursively to remote
      uses: garygrossgarten/github-action-scp@release
      with:
          local: ./CrowbarWebsite/bin/Release/net5.0/linux-x64
          remote: /var/www/websiteapp
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          privateKey: ${{ secrets.PRIVATEKEY }}
    - name: Restart website
      uses: garygrossgarten/github-action-ssh@v0.6.3
      with:
          command: sudo systemctl start crowbarwebsite.service
          host: ${{ secrets.HOST }}
          username: deployaccount
          privateKey: ${{ secrets.PRIVATEKEY }}   
